# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# Add or remove your plugins here:
# [[plugins]]
# repo = 'Shougo/neosnippet.vim'
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# [[plugins]]
# repo = 'mattn/emmet-vim'

# You can specify revision/branch/tag.
# [[plugins]]
# repo = 'Shougo/vimshell'

# 補完機能
# repo = 'marcus/rsense'
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'
# repo = 'violetyk/neocomplete-php.vim'
# [[plugins]]

# JavaScript "
# [[plugins]]
# repo = 'othree/yajs.vim'

# icon設定
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'
# nerdTree "
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# Ruby "
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'tpope/vim-surround'

# Rails "
# [[plugins]]
# repo = 'tpope/vim-rails'
# [[plugins]]
# repo = 'basyura/unite-rails'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# 日本語ヘルプ
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# IDE化
[[plugins]]
repo = 'Shougo/unite.vim'
# [[plugins]]
# repo = 'vim-scripts/taglist.vim'

# 状態自動保存・復帰
[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

# 日本語入力系
# repo = 'tyru/eskk.vim'
# repo = 'fuenor/im_control.vim'

# コメント系
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 検索系
# :Unite file_mruを使えるように
# [[plugins]]
# repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'rking/ag.vim'

# [[plugins]]
# repo = 'vim-scripts/vimgrep.vim'
repo = 'ngmy/vim-rubocop'

# Shell
# repo = 'Shougo/vimshell'
# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# [[plugins]]
# repo = 'thinca/vim-quickrun'

# Markdown
# [[plugins]]
# repo = 'AtsushiSakai/myvim'
# [[plugins]]
# repo = 'kannokanno/previm'
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# [[plugins]]
# repo = 'tyru/open-browser.vim'
# table作成
# [[plugins]]
# repo = 'ywatase/mdt.vim'

# color設定
# [[plugins]]
# repo    = 'vim-airline/vim-airline'
# depends = ['vim-airline-themes']
#
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# [[plugins]]
# repo = 'tomasr/molokai'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'Lokaltog/vim-powerline'
[[plugins]]
repo = 'powerline/powerline'
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Diff
# [[plugins]]
# repo = 'vim-scripts/DirDiff.vim'

# 画面リサイズ
[[plugins]]
repo = 'simeji/winresizer'

# インデント視覚化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Filer
[[plugins]]
repo = 'Shougo/vimfiler'

# 文法チェック
[[plugins]]
repo = 'w0rp/ale'
