# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# 移動
# [[plugins]]
# repo = 'rhysd/accelerated-jk'

# You can specify revision/branch/tag.
# [[plugins]]
# repo = 'Shougo/vimshell'

# JavaScript "
# [[plugins]]
# repo = 'othree/yajs.vim'

# Programming language
[[plugins]]
repo = 'sheerun/vim-polyglot'

# icon設定
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# nerdTree "
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# %拡張
# [[plugins]]
# repo = 'tmhedberg/matchit'
# [[plugins]]
# repo = 'vimtaku/hl_matchit.vim'

# Rails "
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
[[plugins]]
repo = '5t111111/denite-rails'

# Tag
# [[plugins]]
# repo = 'soramugi/auto-ctags.vim'
# [[plugins]]
# repo = 'zebult/auto-gtags.vim'
# [[plugins]]
# repo = 'lighttiger2505/gtags.vim'
# [[plugins]]
# repo = '5t111111/alt-gtags.vim'
# [[plugins]]
# repo = 'tpope/vim-bundler'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 日本語ヘルプ
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# IDE化
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'majutsushi/tagbar'

# 状態自動保存・復帰
# [[plugins]]
# repo = 'xolox/vim-session'
# depends = ['xolox/vim-misc']

# [[plugins]]
# repo = 'xolox/vim-misc'

# 日本語入力系
# repo = 'tyru/eskk.vim'
# repo = 'fuenor/im_control.vim'

# 要らない??
# [[plugins]]
# repo = 'ngmy/vim-rubocop'

# Shell
# repo = 'Shougo/vimshell'
# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# [[plugins]]
# repo = 'thinca/vim-quickrun'

# Markdown
# [[plugins]]
# repo = 'AtsushiSakai/myvim'
# [[plugins]]
# repo = 'kannokanno/previm'
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# [[plugins]]
# repo = 'tyru/open-browser.vim'
# table作成
# [[plugins]]
# repo = 'ywatase/mdt.vim'

# color設定
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
# [[plugins]]
# repo = 'vim-scripts/AnsiEsc.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Diff
# [[plugins]]
# repo = 'vim-scripts/DirDiff.vim'

# インデント視覚化
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'

# Filer
# [[plugins]]
# repo = 'Shougo/vimfiler'

# 文法チェック
[[plugins]]
repo = 'w0rp/ale'

# ブラウザ検索
# [[plugins]]
# repo = 'tyru/open-browser.vim'

# コメント系
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 検索系
# :Unite file_mruを使えるように
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'rking/ag.vim'

# 画面リサイズ
[[plugins]]
repo = 'simeji/winresizer'

# 検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star)
nmap # <Plug>(anzu-sharp)
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'

# 置換
[[plugins]]
repo = 'osyo-manga/vim-over'

# yank
[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
'''

# [[plugins]]
# repo = 'kien/ctrlp.vim'
