# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# 移動
# [[plugins]]
# repo = 'rhysd/accelerated-jk'

# Add or remove your plugins here:
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'mattn/emmet-vim'

# You can specify revision/branch/tag.
# [[plugins]]
# repo = 'Shougo/vimshell'

# 補完機能
[[plugins]]
repo = 'Shougo/neocomplcache.vim'
[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'
# [[plugins]]
# repo = 'violetyk/neocomplete-php.vim'
[[plugins]]
repo = 'cohama/lexima.vim'

# JavaScript "
# [[plugins]]
# repo = 'othree/yajs.vim'

# icon設定
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# nerdTree "
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# Ruby "
[[plugins]]
repo = 'tpope/vim-endwise'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'AndrewRadev/switch.vim'
[[plugins]]
repo = 't9md/vim-quickhl'
# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# [[plugins]]
# repo = 'vim-scripts/ruby-matchit'
# [[plugins]]
# repo = 'todesking/ruby_hl_lvar.vim'
# refactoring
# [[plugins]]
# repo = 'ecomba/vim-ruby-refactoring'

# %拡張
[[plugins]]
repo = 'tmhedberg/matchit'
[[plugins]]
repo = 'vimtaku/hl_matchit.vim'

# Rails "
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
[[plugins]]
repo = '5t111111/denite-rails'
[[plugins]]
repo = 'basyura/unite-rails'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 日本語ヘルプ
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# IDE化
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'majutsushi/tagbar'

# 状態自動保存・復帰
[[plugins]]
repo = 'xolox/vim-session'
depends = ['xolox/vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

# 日本語入力系
# repo = 'tyru/eskk.vim'
# repo = 'fuenor/im_control.vim'

# コメント系
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 検索系
# :Unite file_mruを使えるように
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'rking/ag.vim'
[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'ngmy/vim-rubocop'

# Shell
# repo = 'Shougo/vimshell'
# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# [[plugins]]
# repo = 'thinca/vim-quickrun'

# Markdown
# [[plugins]]
# repo = 'AtsushiSakai/myvim'
# [[plugins]]
# repo = 'kannokanno/previm'
# [[plugins]]
# repo = 'plasticboy/vim-markdown'
# [[plugins]]
# repo = 'tyru/open-browser.vim'
# table作成
# [[plugins]]
# repo = 'ywatase/mdt.vim'

# color設定
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = 'Townk/vim-autoclose'
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
[[plugins]]
repo = 'junegunn/vim-easy-align'

# Diff
# [[plugins]]
# repo = 'vim-scripts/DirDiff.vim'

# 画面リサイズ
[[plugins]]
repo = 'simeji/winresizer'

# インデント視覚化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Filer
# [[plugins]]
# repo = 'Shougo/vimfiler'

# 文法チェック
[[plugins]]
repo = 'w0rp/ale'

# f検索強化
[[plugins]]
repo = 'rhysd/clever-f.vim'

# ブラウザ検索
[[plugins]]
repo = 'tyru/open-browser.vim'

# 置換
[[plugins]]
repo = 'osyo-manga/vim-over'
