# Let dein manage dein
# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# 移動
# [[plugins]]
# repo = 'rhysd/accelerated-jk'

# You can specify revision/branch/tag.
# [[plugins]]
# repo = 'Shougo/vimshell'

# JavaScript "
# [[plugins]]
# repo = 'othree/yajs.vim'

# Programming language
[[plugins]]
repo = 'sheerun/vim-polyglot'

# icon設定
[[plugins]]
repo = 'ryanoasis/vim-devicons'
# nerdTree "
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# %拡張
# [[plugins]]
# repo = 'tmhedberg/matchit'
# [[plugins]]
# repo = 'vimtaku/hl_matchit.vim'

# Rails "
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
[[plugins]]
repo = '5t111111/denite-rails'

# indentなど
# [[plugins]]
# repo = 'scrooloose/vimfiles'

# Tag
# [[plugins]]
# repo = 'alpaca-tc/alpaca_tags'
# [[plugins]]
# repo = 'soramugi/auto-ctags.vim'
# [[plugins]]
# repo = 'zebult/auto-gtags.vim'
# [[plugins]]
# repo = 'lighttiger2505/gtags.vim'
# [[plugins]]
# repo = '5t111111/alt-gtags.vim'
# [[plugins]]
# repo = 'tpope/vim-bundler'
[[plugins]]
repo = 'tsukkee/unite-tag'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'hewes/unite-gtags'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# 日本語ヘルプ
# [[plugins]]
# repo = 'vim-jp/vimdoc-ja'

# IDE化
[[plugins]]
repo = 'junegunn/fzf.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'majutsushi/tagbar'

# メモ帳
# [[plugins]]
# repo = 'Shougo/junkfile.vim'

# 状態自動保存・復帰
# [[plugins]]
# repo = 'xolox/vim-session'
# depends = ['xolox/vim-misc']
[[plugins]]
repo = 'manasthakur/vim-sessionist'
# [[plugins]]
# repo = 'Shougo/unite-session'

# [[plugins]]
# repo = 'xolox/vim-misc'

# 日本語入力系
# repo = 'tyru/eskk.vim'
# repo = 'fuenor/im_control.vim'

# 要らない??
# [[plugins]]
# repo = 'ngmy/vim-rubocop'

# Shell
# repo = 'Shougo/vimshell'
# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# [[plugins]]
# repo = 'thinca/vim-quickrun'

# Markdown
# [[plugins]]
# repo = 'AtsushiSakai/myvim'
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
# table作成
# [[plugins]]
# repo = 'ywatase/mdt.vim'

# color設定
[[plugins]]
repo = 'raphamorim/lucario'
# repo = 'tomasr/molokai'
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
# [[plugins]]
# repo = 'vim-scripts/AnsiEsc.vim'
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Diff
# [[plugins]]
# repo = 'vim-scripts/DirDiff.vim'

# インデント視覚化
# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'

# Filer
# [[plugins]]
# repo = 'Shougo/vimfiler'

# 文法チェック
[[plugins]]
repo = 'w0rp/ale'

# ブラウザ検索
# [[plugins]]
# repo = 'tyru/open-browser.vim'

# コメント系
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 検索系
# :Unite file_mruを使えるように
[[plugins]]
repo = 'Shougo/neomru.vim'
# vimrc整理後,消したい
# [[plugins]]
# repo = 'rking/ag.vim'
# [[plugins]]
# repo = 'jremmen/vim-ripgrep'
# ag, ripgrep両方入ってる
# [[plugins]]
# repo = 'yegappan/grep'

# 画面リサイズ
[[plugins]]
repo = 'simeji/winresizer'

# 検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
nmap n <Plug>(anzu-n-with-echo)
nmap N <Plug>(anzu-N-with-echo)
nmap * <Plug>(anzu-star)
nmap # <Plug>(anzu-sharp)
'''

# [[plugins]]
# repo = 't9md/vim-quickhl'

[[plugins]]
repo = 'rhysd/clever-f.vim'

# 置換
[[plugins]]
repo = 'osyo-manga/vim-over'

# yank
# [[plugins]]
# repo = 'LeafCage/yankround.vim'
# hook_add = '''
# '''

# [[plugins]]
# repo = 'kien/ctrlp.vim'

# [[plugins]]
# repo = 'Shougo/neco-syntax'

# Rubyの自動補完
# [[plugins]]
# repo = 'Shougo/deoplete-rct'
# on_ft = ['ruby']
# [[plugins]]
# repo = 'fishbullet/deoplete-ruby'
# on_ft = ['ruby']

# Rubyの自動補完
# [[plugins]]
# repo = 'osyo-manga/vim-monster'
# hook_add = '''
# let g:monster#completion#rcodetools#backend = "async_rct_complete"
# let g:deoplete#sources#omni#input_patterns = {
#   \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
#   \}
# '''

# [[plugins]]
# repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
# on_event = ['InsertEnter']
# on_source = ['Shougo/deoplete.vim']
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
# on_event = ['InsertEnter']
# on_source = ['Shougo/neosnippet.vim']

# 絵文字
# [[plugins]]
# repo = 'mattn/emoji-vim'

# buffer
# 後々導入
# [[plugins]]
# repo = 'ap/vim-buftabline'

# mark
[[plugins]]
repo = 'jacquesbh/vim-showmarks'

# 補完
[[plugins]]
repo = 'ervandew/supertab'
